In [1]:
import pandas as pd
import re

## load data

In [2]:
data = pd.read_json('~/data/ner_labeled_tg_messages.json')

In [3]:
len(data)

844

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 844 entries, 0 to 843
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     844 non-null    int64
 1   annotations            844 non-null    object
 2   file_upload            844 non-null    object
 3   drafts                 844 non-null    object
 4   predictions            844 non-null    object
 5   data                   844 non-null    object
 6   meta                   844 non-null    object
 7   created_at             844 non-null    datetime64[ns, UTC]
 8   updated_at             844 non-null    datetime64[ns, UTC]
 9   inner_id               844 non-null    int64
 10  total_annotations      844 non-null    int64
 11  cancelled_annotations  844 non-null    int64
 12  total_predictions      844 non-null    int64
 13  project                844 non-null    int64
 14  updated_by             844 non-null    int64
dtypes: datetime64[ns, UTC](2), int64(7), object(6)
memory usage: 99.0+ KB

## drop skipped tasks

In [5]:
df = data.copy()

In [6]:
print(len(df[df['cancelled_annotations']==1]),  'skipped annotations in dataframe.')

344 skipped annotations in dataframe.

In [7]:
print(len(df[df['cancelled_annotations']==0]),  'valid annotations in dataframe.')

500 valid annotations in dataframe.

In [8]:
df = df[df['cancelled_annotations']==0]

## reduce to necessary columns

In [9]:
df = df[['id', 'annotations', 'data']]

## explode nested columns containing annotations and data

In [10]:
df = df.explode('annotations', 'data')

## extract results from annotations column

In [11]:
df['annotation_results'] = df.annotations.apply(lambda x: x['result'] if len(x) > 0 else None)

## extract cleaned_text, custom_id from data column

In [12]:
df['text'] = df['data'].apply(lambda x: x['cleaned_text'] if len(x)> 0 else None)

In [13]:
df['custom_id'] = df['data'].apply(lambda x: x['id'] if len(x)> 0 else None)

## tokenize

In [14]:
df['tokens'] = df.text.apply(lambda x: x.split())

## tokenize text and get span for each token

In [15]:
def tokenize_and_get_spans(text): 
    
    result = []
    
    tokens = text.split()
    
    for token in tokens: 
        
        span = re.search(re.escape(token), text).span()
        start = span[0]
        end = span[1]
        token_start = token + str(start)
        result.append([{'token': token,
                        'start': start,
                       'end': end}])
    return result

In [16]:
df['tokens_with_spans'] = df.text.apply(lambda x: tokenize_and_get_spans(x))

In [17]:
df.head()

,id,annotations,data,annotation_results,text,custom_id,tokens,tokens_with_spans
0,25063,"{'id': 6929, 'completed_by': 6, 'result': [{'v...","{'Unnamed: 0': 304, 'id': 'Demotermine12502886...","[{'value': {'start': 0, 'end': 10, 'text': 'Re...",Reutlingen Marktplatz Bitte beachten ‼️ Vom Or...,Demotermine125028861045762020-12-17 11:25:47,"[Reutlingen, Marktplatz, Bitte, beachten, ‼️, ...","[[{'token': 'Reutlingen', 'start': 0, 'end': 1..."
1,25062,"{'id': 6928, 'completed_by': 6, 'result': [{'v...","{'Unnamed: 0': 303, 'id': 'Demotermine12502886...","[{'value': {'start': 24, 'end': 33, 'text': 'S...",Die Trommeln rufen nach Straßburg RufderTromme...,Demotermine1250288610148002021-08-25 03:01:37,"[Die, Trommeln, rufen, nach, Straßburg, Rufder...","[[{'token': 'Die', 'start': 0, 'end': 3}], [{'..."
2,25061,"{'id': 6927, 'completed_by': 6, 'result': [{'v...","{'Unnamed: 0': 302, 'id': 'Demotermine12502886...","[{'value': {'start': 0, 'end': 6, 'text': 'Dan...",Daniel und der Bürgermeister - Brackenheim 29....,Demotermine1250288610303822021-12-06 15:06:02,"[Daniel, und, der, Bürgermeister, -, Brackenhe...","[[{'token': 'Daniel', 'start': 0, 'end': 6}], ..."
3,25060,"{'id': 6926, 'completed_by': 6, 'result': [{'v...","{'Unnamed: 0': 301, 'id': 'Demotermine12502886...","[{'value': {'start': 25, 'end': 44, 'text': '#...",#Leserzuschrift #BRV2510 #Lichterspaziergang @...,Demotermine1250288610233692021-10-26 09:47:32,"[#Leserzuschrift, #BRV2510, #Lichterspaziergan...","[[{'token': '#Leserzuschrift', 'start': 0, 'en..."
4,25059,"{'id': 6925, 'completed_by': 6, 'result': [{'v...","{'Unnamed: 0': 300, 'id': 'Demotermine12502886...","[{'value': {'start': 44, 'end': 46, 'text': '3...",✅ BITTE FLYER TEILEN ! Ort geändert für den 3....,Demotermine1250288610171062021-09-04 20:37:53,"[✅, BITTE, FLYER, TEILEN, !, Ort, geändert, fü...","[[{'token': '✅', 'start': 0, 'end': 1}], [{'to..."

In [18]:
def explode_and_add_ner_tags(df):
    
    final_df = pd.DataFrame()
    
    for i in df.index: 
        
        result = {}
        
        single_df = pd.DataFrame(columns=['custom_id', 'token', 'start', 'end', 'ner_tag'])
    
        curr = df.iloc[i]
        
        tokens = curr.tokens
        
        text = curr.text
        
        annotation_results = curr.annotation_results
    
        for token in tokens:
                span = re.search(re.escape(token), text).span()
                result[span] = {'token': token, 'ner_tag': 'O'}
                result[span]['start'] = span[0]
                result[span]['end'] = span[1]
        
        for x in annotation_results:
                tagged_text = x['value']['text']
                span_tag = ((x['value']['start']),(x['value']['end']))
                curr_ner_tag = x['value']['labels'][0]     
                    
                if span_tag in result.keys():
                    result[span_tag]['ner_tag'] = curr_ner_tag
                    result[span_tag]['tagged_text'] = tagged_text
    
        data = pd.DataFrame(result).transpose()
        data['custom_id'] = curr.custom_id

        final_df = pd.concat([final_df, data], axis=0)
    
    return final_df[['custom_id', 'token', 'ner_tag', 'start', 'end']].reset_index(drop=True)

In [19]:
result = explode_and_add_ner_tags(df)

In [20]:
len(result)

16373

In [21]:
result

,custom_id,token,ner_tag,start,end
0,Demotermine125028861045762020-12-17 11:25:47,Reutlingen,B-LOC,0,10
1,Demotermine125028861045762020-12-17 11:25:47,Marktplatz,B-LOC,11,21
2,Demotermine125028861045762020-12-17 11:25:47,Bitte,O,22,27
3,Demotermine125028861045762020-12-17 11:25:47,beachten,O,28,36
4,Demotermine125028861045762020-12-17 11:25:47,‼️,O,37,39
...,...,...,...,...,...
16368,Demotermine12502886104122,Existenzen,O,34,44
16369,Demotermine12502886104122,erhalten,O,45,53
16370,Demotermine12502886104122,!,O,54,55
16371,Demotermine12502886104122,@StuttgartGrundgesetzdemos,O,56,82
16372,Demotermine12502886104122,@Corona_Reset,O,83,96

In [22]:
result.groupby('ner_tag').size()

ner_tag
B-ACTION      305
B-DATE        423
B-LOC        1279
B-ORG         176
B-PER         110
B-TIME        216
I-ACTION       30
I-DATE        147
I-LOC         398
I-ORG          66
I-PER          65
I-TIME         96
O           13062
dtype: int64

## put it back together to prepare for transformers

In [23]:
ids = set(result.custom_id.values)

In [24]:
len(ids)

500

In [25]:
result = result.set_index(['custom_id'])

In [26]:
dataset = pd.DataFrame()

for idx in ids:
    
    curr = result.loc[idx]
    temp = {}  
    
    tokens = list(curr.token.values)
    ner_tags = list(curr.ner_tag.values)

    temp[idx] = {
        'ner_tags': ner_tags,
        'tokens' : tokens 
    }
  
    df = pd.DataFrame(temp).transpose()
    df['id'] = idx
    df = df[['id', 'tokens', 'ner_tags']]
    
    dataset = pd.concat([dataset, df], axis=0)

In [27]:
ds = dataset.reset_index(drop=True)

In [28]:
ds.head()

,id,tokens,ner_tags
0,Demotermine1250288610133752021-08-01 10:40:25,"[Berlin, Motorradkorso, Raus, auf, die, Straße...","[B-LOC, B-ACTION, O, O, O, O, O]"
1,Demotermine1250288610252692021-11-06 13:55:24,"[Leipzig, Augustusplatz, ,, 06.11.2021, -, Pol...","[B-LOC, B-LOC, O, B-DATE, O, B-ORG, O, O, O, O..."
2,Demotermine125028861021612020-07-23 19:35:27,"[Murrhardt, Sonntag, ;, 26.07.2020, 15, Uhr, P...","[B-LOC, B-DATE, I-DATE, I-DATE, B-TIME, I-TIME..."
3,Demotermine125028861075532021-03-13 23:28:28,"["", Wir, lassen, uns, unsere, Grundrechte, ,, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,Demotermine1250288610126762021-07-22 23:11:13,"[Bristol, 01082021, Overview, https://t.me/Dem...","[B-LOC, B-DATE, O, O, O, O, O, O, O]"

In [31]:
#ds.to_json('ds_telegram.json')