In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('temp/demotermine_cleaned.csv', parse_dates=['date', 'edit_date'])

# only german

In [16]:
df = df[df['lang'] == 'de']

# min, max text length

In [17]:
df = df[(df['text_length'] >= 100) & (df['text_length'] <= 400)]

In [18]:
len(df)

12690

# select sample

In [19]:
twenty_percent = int(len(df) / 100 * 20)

In [21]:
sample_df = df.sample(twenty_percent, random_state=42)

In [22]:
sample_df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,channel_name,channel_id,channel_description,message_id,from_id,via_bot_id,date,...,forwards,fwd_from,replies,reply_to,media,views,id,cleaned_text,text_length,lang
18616,22078,22078,24675,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,15100,NaN,NaN,2021-08-28 07:38:30,...,2.0,NaN,"MessageReplies(replies=0, replies_pts=290295, ...",NaN,MessageMediaWebPage(webpage=WebPage(id=8720606...,2801.0,Demotermine1250288610151002021-08-28 07:37:48,🐣 🎶 Äußert euch sachlich 28.08.2021 um 09 : 2...,262,de
16997,19929,19929,22186,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,25395,NaN,NaN,2021-11-06 16:33:19,...,23.0,NaN,"MessageReplies(replies=0, replies_pts=290292, ...",NaN,MessageMediaDocument(document=Document(id=5204...,2465.0,Demotermine1250288610253952021-11-06 16:33:43,"Versuch eines Gesprächs mit Stern TV , das von...",133,de
9032,10855,10855,12331,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,16404,NaN,NaN,2021-08-29 15:35:18,...,0.0,NaN,"MessageReplies(replies=0, replies_pts=290293, ...",NaN,MessageMediaPhoto(photo=Photo(id=5865183099078...,2190.0,Demotermine1250288610164042021-08-29 15:33:55,# be2808 13.31Demozug Teil3 # Demokratischer W...,166,de
17788,20935,20935,23398,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,24049,NaN,NaN,2021-10-30 04:09:13,...,2.0,NaN,"MessageReplies(replies=0, replies_pts=290292, ...",NaN,MessageMediaDocument(document=Document(id=5181...,1019.0,Demotermine1250288610240492021-10-30 04:08:39,ICONIC : ADVANCE AUSTRALIA FAIR - AUSTRALIAN A...,189,de
8815,10622,10622,12059,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,16708,NaN,NaN,2021-08-31 19:38:29,...,14.0,NaN,"MessageReplies(replies=1, replies_pts=290293, ...",NaN,MessageMediaPhoto(photo=Photo(id=5294374304693...,4564.0,Demotermine1250288610167082021-08-31 19:45:07,"CUXHAVEN geht spazieren . USER USER 05092021 ,...",103,de

In [25]:
sample_df.to_csv('temp/sample_data.csv')

## Identify similar messages via Levenshtein Distance

In [26]:
from itertools import combinations
import Levenshtein as lev

In [28]:
df = sample_df.copy()

In [29]:
lev_df = pd.DataFrame() 
new_df = pd.DataFrame(combinations(df['cleaned_text'],2), columns=["text_1", "text_2"]) 
new_df["lev_score"] = new_df.apply(lambda x: lev.ratio(x[0],x[1]), axis=1) 
lev_df = pd.concat([lev_df, new_df], axis=0).reset_index(drop=True)

In [30]:
# Get message ids
lev_df_ids = pd.DataFrame() 
new_df_ids = pd.DataFrame(combinations(df['message_id'],2), columns=["message_id_1", "message_id_2"]) 
lev_df_ids = pd.concat([lev_df_ids, new_df_ids], axis=0).reset_index(drop=True)

In [33]:
# combine lev results with message ids 
levs = pd.DataFrame()
levs = pd.concat([lev_df,lev_df_ids], axis=1)

In [35]:
levs.head()

,text_1,text_2,lev_score,message_id_1,message_id_2
0,🐣 🎶 Äußert euch sachlich 28.08.2021 um 09 : 2...,"Versuch eines Gesprächs mit Stern TV , das von...",0.372796,15100,25395
1,🐣 🎶 Äußert euch sachlich 28.08.2021 um 09 : 2...,# be2808 13.31Demozug Teil3 # Demokratischer W...,0.412993,15100,16404
2,🐣 🎶 Äußert euch sachlich 28.08.2021 um 09 : 2...,ICONIC : ADVANCE AUSTRALIA FAIR - AUSTRALIAN A...,0.251656,15100,24049
3,🐣 🎶 Äußert euch sachlich 28.08.2021 um 09 : 2...,"CUXHAVEN geht spazieren . USER USER 05092021 ,...",0.295082,15100,16708
4,🐣 🎶 Äußert euch sachlich 28.08.2021 um 09 : 2...,# Helvetia Rundgang Ascona 27.10.21 — Guido Bö...,0.301075,15100,23667

In [37]:
# get ids of messages over certain threshold
second_ids = levs[levs['lev_score'] >= 0.8].message_id_2.tolist()

In [40]:
len(set(second_ids))

642

In [44]:
ids_to_drop = list(set(second_ids))

In [48]:
result_df = df[~df.message_id.isin(ids_to_drop)]

In [49]:
len(result_df)

1896

In [50]:
result_df.to_csv('temp/data_selection.csv')

In [51]:
result_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1896 entries, 18616 to 6690
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0.2         1896 non-null   int64
 1   Unnamed: 0.1         1896 non-null   int64
 2   Unnamed: 0           1896 non-null   int64
 3   channel_name         1896 non-null   object
 4   channel_id           1896 non-null   int64
 5   channel_description  1896 non-null   object
 6   message_id           1896 non-null   int64
 7   from_id              0 non-null      float64
 8   via_bot_id           0 non-null      float64
 9   date                 1896 non-null   datetime64[ns]
 10  edit_date            1824 non-null   datetime64[ns]
 11  text                 1896 non-null   object
 12  forwards             1896 non-null   float64
 13  fwd_from             121 non-null    object
 14  replies              1760 non-null   object
 15  reply_to             1 non-null      object
 16  media                1826 non-null   object
 17  views                1896 non-null   float64
 18  id                   1896 non-null   object
 19  cleaned_text         1896 non-null   object
 20  text_length          1896 non-null   int64
 21  lang                 1896 non-null   object
dtypes: datetime64[ns](2), float64(4), int64(6), object(10)
memory usage: 340.7+ KB

In [53]:
columns_to_keep = ['id', 'message_id', 'date', 'cleaned_text', 'lang']

In [55]:
result_df = result_df[columns_to_keep]

In [58]:
result_df.head(20)

,id,message_id,date,cleaned_text,lang
18616,Demotermine1250288610151002021-08-28 07:37:48,15100,2021-08-28 07:38:30,🐣 🎶 Äußert euch sachlich 28.08.2021 um 09 : 2...,de
16997,Demotermine1250288610253952021-11-06 16:33:43,25395,2021-11-06 16:33:19,"Versuch eines Gesprächs mit Stern TV , das von...",de
9032,Demotermine1250288610164042021-08-29 15:33:55,16404,2021-08-29 15:35:18,# be2808 13.31Demozug Teil3 # Demokratischer W...,de
17788,Demotermine1250288610240492021-10-30 04:08:39,24049,2021-10-30 04:09:13,ICONIC : ADVANCE AUSTRALIA FAIR - AUSTRALIAN A...,de
8815,Demotermine1250288610167082021-08-31 19:45:07,16708,2021-08-31 19:38:29,"CUXHAVEN geht spazieren . USER USER 05092021 ,...",de
17994,Demotermine1250288610236672021-10-28 08:39:51,23667,2021-10-28 08:40:17,# Helvetia Rundgang Ascona 27.10.21 — Guido Bö...,de
11918,Demotermine1250288610119712021-06-28 17:40:13,11971,2021-06-28 17:40:13,"Aliens , Bullen-Fatzen , Eskalation , Feiern b...",de
23437,Demotermine125028861022352020-07-31 12:43:03,2235,2020-07-31 12:39:41,Achtung ! Ganz wichtige Mitteilung für die Dem...,de
7512,Demotermine1250288610187112021-09-20 23:51:34,18711,2021-09-20 23:46:07,📆 Mahnwache / Versammlung unter freiem Himmel ...,de
8198,Demotermine1250288610176552021-09-10 14:40:45,17655,2021-09-10 14:40:04,"Osnabrück , Montagsdemo , 13.9.2021. Diesmal w...",de
13707,Demotermine125028861095632021-04-27 03:58:36,9563,2021-04-27 03:57:02,Es geht weiter - jetzt erst recht ! Markiert e...,de
3413,Demotermine1250288610290942021-11-30 21:15:12,29094,2021-11-30 21:15:09,YOUTUBE / Wie können die Aufrufzahlen sinken ?...,de
11458,Demotermine1250288610125302021-07-18 09:30:10,12530,2021-07-18 09:24:21,Hier könnt ihr eine Helferdemo telefonisch anm...,de
7707,Demotermine1250288610183832021-09-18 13:38:20,18383,2021-09-18 13:38:57,URL 100'000 Leute in Winterthur 18.9.21 Kanal ...,de
1188,Demotermine1250288610323462021-12-18 18:44:35,32346,2021-12-18 18:44:32,TROTZ ALLEM : TAUSENDE DEMONSTRIEREN IN COTTBU...,de
20563,Demotermine125028861035432020-11-04 10:13:35,3543,2020-11-04 10:12:41,Querdenken 713 Mittwoch 04.11.2020 17:00 bis 1...,de
4207,Demotermine125028861067622021-02-25 01:02:50,6762,2021-02-25 01:02:15,Hofheimer Unternehmer habt Mut - Schließt euch...,de
8573,Demotermine1250288610170422021-09-04 10:44:02,17042,2021-09-03 12:17:01,"Das Merkel kam kurzfristig , um Fragestellern ...",de
13287,Demotermine1250288610101512021-05-07 02:43:20,10151,2021-05-07 02:42:25,Kassel Auto- und Fahrraddemo USER 07052021 - 1...,de
13266,Demotermine1250288610101762021-05-07 13:25:29,10176,2021-05-07 13:24:43,Videobeschreibung : Eltern bitten Soldaten um ...,de

In [57]:
# result_df.to_csv('temp/data_selection_final.csv')

In [59]:
texts = result_df.cleaned_text.values

In [62]:
for t in texts: 
    print(t, '\n\n')

🐣 🎶 Äußert euch sachlich 28.08.2021 um 09 : 25 Uhr Deine Meinung zum Reichstagsstürmchen 2020 ? Sag der Bild-Zeitung bitte auf Twitter sachlich Deine Meinung zu diesem Thema bitte : URL # lernetweeten # rausausderblase Alexander Ehrlich Raus auf die Straßen USER


Versuch eines Gesprächs mit Stern TV , das von der Polizei unterbunden wird . USER Raus auf die Straßen USER 👉 Übersicht / Overview 👈


# be2808 13.31Demozug Teil3 # Demokratischer Widerstand erreicht wider # Demoverbot Brunnenstraße — Osnabrücker Sommer der Aufklärung URL 2:17 Raus auf die Straßen USER


ICONIC : ADVANCE AUSTRALIA FAIR - AUSTRALIAN ANTHEM [ LIVE VIOLIN ACOUSTIC VERSION ] MELBOURNE , AUSTRALIA 30.10.21 RISE UP MELBOURNE USER Raus auf die Straßen USER 👉 Übersicht / Overview 👈


CUXHAVEN geht spazieren . USER USER 05092021 , 12092021 , 19092021 , 26092021 Raus auf die Straßen USER


# Helvetia Rundgang Ascona 27.10.21 — Guido Böni URL 3:33 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Aliens , Bullen-Fatzen , Eskalation , Feiern beseitigt jede Spaltung , EM , Hasenheide , Prenzlauer Berg — Freedom Parade mit Captain Future URL 10:46 Raus auf die Straße USER


Achtung ! Ganz wichtige Mitteilung für die Demo morgen in Berlin in meiner Sprachnachricht auf Telegram . Zensursicher USER ( YouTube Backup ) USER - Bilder und Videos hochladen USER - Diskussion USER Fahren oder Mitfahren USER - Übernachten ? USER


📆 Mahnwache / Versammlung unter freiem Himmel 👉 🏻 mehr Infos dazu # Termin Murrhardt USER 23092021 # BW Raus auf die Straßen USER


Osnabrück , Montagsdemo , 13.9.2021. Diesmal wieder vor dem Rathaus , weil das Theater bis zum 1.10. anderweitig belegt ist ! 18.00 Uhr Treffen vor dem Rathaus , dann " kleiner Demoumzug " über den Neumarkt , ca. 19.00 Uhr Kundgebung vor dem Rathaus . Wir freuen uns auf Euch ! USER 13092021 Raus auf die Straßen USER


Es geht weiter - jetzt erst recht ! Markiert euch gerne schon Mal Sa den 15. Mai in eurem Kalender - genauere Infos folgen ! In Kooperation mit den weltweiten Demonstrationen , lasst euch überraschen ! 🥳 🥁 💪 # esreicht # d1505 # wirwerdenalledasein USER 15052021 Raus auf die Straße USER


YOUTUBE / Wie können die Aufrufzahlen sinken ? ? ? — Papst Alwin / alwinproduction URL 1:15 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Hier könnt ihr eine Helferdemo telefonisch anmelden . Gerne dürfen es auch viele Demos sein überall dort , wo Hilfe gebraucht wird . Sendet eure Termine USER Aufruf URL Raus auf die Straße USER


URL 100'000 Leute in Winterthur 18.9.21 Kanal : URL Aufarbeitungsinitiative : URL Raus auf die Straßen USER


TROTZ ALLEM : TAUSENDE DEMONSTRIEREN IN COTTBUS Obwohl die Brandenburger Landesregierung nun auch das Versammlungsrecht versucht zu beschneiden , demonstrieren heute erneut Tausende - teils in mehreren Demonstrationszügen - in Cottbus für die Freiheit und gegen Staatswillkür . Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Querdenken 713 Mittwoch 04.11.2020 17:00 bis 19:00 Uhr Stadtpark 74172 Neckarsulm URL Weitere Infos : URL USER USER Bilder und Videos hochladen USER - Termine in Textform USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


Hofheimer Unternehmer habt Mut - Schließt euch an ! Wir für euch und ihr für uns , gemeinsam als Menschheitsfamilie 🙏 # ihrseidnichtalleine # Hofheimstehtauf Quelle : URL Raus auf die Straße USER


Das Merkel kam kurzfristig , um Fragestellern zu entgehen . Der Wasserwerfer wird für die Befüllung von kleineren Trinkwassertanks und zur Staubbindung der Straßen hier mal sinnvoll eingesetzt . Heute kann er auch zur Sicherheit für Mutti dagewesen sein . Mehr URL Raus auf die Straßen USER


Kassel Auto- und Fahrraddemo USER 07052021 - 14052021 - 21052021 - 28052021 Raus auf die Straße USER


Videobeschreibung : Eltern bitten Soldaten um Schutz ihrer Kinder . YouTube hat dieses Video gesperrt ❗ ❗ ❗ ❗ Mehr USER Raus auf die Straße USER


Er ist wieder zurück , sogar in Leipzig . SA Antifa . Wehret den Anfängen ! ! ️ Raus auf die Straße USER


Tegernsee Autokorso Start Gmund Volksfestplatz Parkplatz Strandbad USER USER 26122020 Bilder und Videos hochladen USER - Termine in Textform USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


Siehe Videobeschreibung ! Demo Stephansplatz Karlsruhe Freitag 8.10.21 Start 17:30 Uhr — Info URL 1:44 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Die Walliserkanne , der flache Beat Flach ( GLP ) , das Baja-California-Paradox und die Merdien-Bullys 👉 🏻 Neuer Beitrag USER


Frankfurt / Oder - Slubice USER 28112020 Bilder und Videos hochladen USER - Termine in Textform USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


Berlin , 01.07.20 -17.30 Uhr Kanzleramt -19 Uhr Brandenburger Tor USER USER - Bilder und Videos hochladen USER - Diskussion USER Fahren oder Mitfahren USER - Übernachten ? USER


Bauern helfen den Anwohnern , die alles verloren haben . Keine öffentlichen Hilfen oder Hygiene-Vorkehrungen wie Dixie-Toiletten . Sie werden komplett im Stich gelassen vom BRD-Regime . 🚨 🌊 Kanal teilen und folgen , die neuesten Nachrichten und Warnungen hier immer zuerst URL USER Raus auf die Straße USER


Coronamaßnahmen Beenden : Kretchmer Verhaften ! Heute sind Massenproteste in unseren schönen Sachsen gefordert ! Hand in Hand zur Freiheit ! Freie Jugend : Folgt uns auf Telegram ! URL Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Schwerin Live Mo13.12.21 - Freie Impfentscheidung - VOLLER Grunthalplatz Min 1:08:15 Schreibt Gesch — DanBarMV - LIVE Berichte Recherchen Meinung URL 1:37:30 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


+ + + Windeltruppe provoziert am Kessel DANZIGER . Wollen sie wieder junge Frauen schlagen ? + + + # B2908 Raus auf die Straßen USER


Wie aus dem Nichts : Zahllose Corona-Demos in ganz Deutschland Ohne Ankündigung gingen am Montagabend Tausende Menschen in ganz Deutschland auf die Straße , auch in Berlin und Brandenburg . URL Raus auf die Straßen USER 👉 Übersicht / Overview 👈


📆 AUFSTEHEN , HINGEHEN , EINSTEHEN 👉 🏻 mehr Infos dazu # Termin # QuerDenken ! Bad Mergentheim USER 30042021 Raus auf die Straße USER


Michael Ballweg – Rede auf Demonstration von QUERDENKEN-911 Nürnberg am 15.05.2021 — QUERDENKEN-911 Nürnberg URL 23:03 Raus auf die Straße USER


Genf USER Bilder und Videos hochladen USER - USER Fahren oder Mitfahren USER - Übernachten ? USER USER


Die friedlichste " Volksversammlung " die es JE gab . Egal was diese " Kreaturen " in der Regierung probiert haben , ES HAT NICHT FUNKTIONIERT Raus auf die Straßen USER 👉 Übersicht / Overview 👈


WEITERGELEITET ! " ! ! ️Update : Wir bleiben auf der Marschallbrücke , da ist eine große Anzahl Menschen . Der Leipziger Platz ist eine Mausefalle , kann von der Polizei ganz schnell eingekesselt werden .. Besser wir bleiben zusammen . "


Das sind die Spasts , die über unser Leben entscheiden . Idiocracy . Die umfassendsten Infos USER Werde USER jetzt !


! ! ! GROßARTIGE MENSCHEN IN GROßARTIGER STIMMUNG . ! ! ! ES MACHT FREUDE FÜR FREIHEIT UND WAHRHEIT EINZUSTEHEN ! ! ! ES WAR EIN SCHÖNER , ABER AUCH ANSTRENGENDER TAG . IN JEDEM FALL EIN WEITERER , ERFOLGREICH GEMEISTERTER MEILENSTEIN . ! ! ! VERGELT ́S GOTT , DANKE , MERCI ! ! ! — — — — — — — — — — Abonnieren Sie unseren Telegram-Kanal : URL — — — — — — — — — Raus auf die Straßen USER


Auch Zwickau läuft und lässt sich nicht weiter von Kretschmer und Co erpressen ! Raus auf die Straßen USER 👉 Übersicht / Overview 👈


" Live Bremgarten 24.11.2021 - Fackelspaziergang " — Sabine Seibold URL 1:55:16 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Taxi Demo 13.03. Berlin Treffpunkt Scheidemannstraße vor dem Bundestag Nein zu Scheuer's PBefG Vorbestellfrist für alle Mietwagen-Vermittlungsdienste Übersicht URL USER 13032021 Bilder und Videos hochladen USER - Termine in Textform USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


Live 2 : Demo gegen Polizeigewalt 11.09.2021 Dresde # dd1109 — QUERDENKEN 351 - Dresden URL 4:22:16 Raus auf die Straßen USER


LIVE aus Zwönitz 8.11.2021 Berichterstattung ( gemäß des ) Grundgesetzes Art.5 — SchwarzRotGold TV URL 1:09:08 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


89150 Laichingen 05.04.2021 um 18Uhr Demozug durch Laichingen mit anschließender Kundgebung USER 05042021 Raus auf die Straße USER


Dortmund Autokorso Start Parkplatz P1 Westfalenpark am Veranstaltungszentrum USER USER USER USER USER 23022021 Bilder und Videos hochladen USER - Termine in Textform USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


Krankenpfleger hat viele Menschen an Covid sterben gesehen und ist trotzdem gegen die Maßnahmen . — Offene Gesellschaft Kurpfalz URL 9:46 Raus auf die Straße USER


Am Potsdamer Platz wurde ein blauer Bus von der Polizei festgesetzt , mir wurde gerade mitgeteilt , dass dort ein Anwalt benötigt wird . USER Video URL Raus auf die Straßen USER


Eine Mutter erzählt von einem Erlebnis in der Schule ihres Sohnes . Uns fehlen die Worte , wie man Kinder so diskriminieren und ausgrenzen kann ! Und alle machen mit , der Lehrer , die Eltern der anderen Kinder .... IST DAS WIRKLICH EURE NORMALITÄT ? WIE WEIT GEHT IHR NOCH ? WANN SEID IHR FALSCH ABGEBOGEN ? Quelle : Netzfund USER


Islamistische Anschlagspläne auf Synagoge in Hagen ? Ermittlungen laufen — Epoch Times Nachrichten URL 3:51 Raus auf die Straßen USER


Hier das Video der heutigen super tollen Demo in Trier , die sehr , sehr friedlich , aber durch Schikanen der Polizei und des Ordnungsamtes Trier ständig gestört wurde . Von der Antifa und dem solidarischen Trier hat man kaum etwas gehört - Frage : " geht denen das Personal aus , weil keine Kohle mehr gibt " ? Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Demo in 22926 Ahrensburg Von Querdenken 410 - Ahrensburg Eltern stehen auf Ärzte für Aufklärung u.v.m. Beginn ab 9:00 Uhr ! Kommt bitte zahlreich , Danke . USER 24102020 Bilder und Videos hochladen USER - USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


Mengen Lichtspaziergang Treffpunkt am Brunnen beim Rathaus USER USER USER 08032021 Raus auf die Straße USER


Gerichte wollen Merkel-Kritiker mundtot machen ! Helft mir ! Aus einem Opfer wird ein Täter gemacht ! — Silberjunge URL 10:37 USER


📆 Schilderaktion als Aufzug durch die Innenstadt Stuttgart 👉 🏻 mehr Infos dazu # Termin Raus auf die Straßen USER


Biochemiker Dr. Steidl über Wirk- und Versagensmechanismen der Covid-Imp-phung — Antihygienista - Offene Gesellschaft Kurpfalz URL 30:25 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


„ Mittlerweile ca. 60 - 100 Mannschaftswagen Richtung Brandenburger Tor . “ USER Offenbar soll auch mit Wasserwerfern das Grippe-Virus , bekämpft werden , welches Anfang 2020 an Corona verstarb ... Raus auf die Straße USER


Berlin 1. August 2021 rund 1 Uhr nachts | Club Matrix — Demokratischer Widerstand URL 0:09 Raus auf die Straße USER


📣 VERANSTALTUNG Miltenberg , Sonntag den 19.12.2021 ' Wir laufen und zeigen , dass wir immer mehr werden , die mit dem Maßnahmen nicht einverstanden sind . ' Start : 14.00 Uhr am alten Bahnhof # Miltenberg # BY # So1912 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Fischerwirt Promovideo fürs Volksbegehren # Bayern Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Auch nächsten Freitag gehen wir wieder Spazieren ! Egal ob mit oder ohne Polizei ! 19 Uhr an der Grundschule in Wünschendorf / Elster * Wer eine Deutschlandflagge hat , kann sie gerne mitbringen ! Deutschlandflaggen sind erwünscht ! 🇩 🇪 📢 USER USER 11062021 Raus auf die Straße USER


Demo für Frieden und Freiheit , Fulda SchotterParkplatz , Johannisstr . / Neuenbergerstr Auestadion , 13. Juni 2020 14 - 16 Uhr USER USER - Bilder und Videos hochladen USER - Diskussion USER Fahren oder Mitfahren USER


Ich bin am Samstag , den 6.11.2021 , um 15:00 Uhr auf dem Augustusplatz in Leipzig . Route Aufzug : Mittlerer Ring ( wie 2020 ) . Und wo seid Ihr ? Bewege Dich selbst , statt bewegt zu werden ! Lasst uns gemeinsam Geschichte wiederholen ! USER USER USER # SN # Sa0611 # Leipzig Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Rechtsanwalt : Jahrelang waren ihnen die Alten egal , jetzt rufen Politiker nach Solidarität . Wieso ? — Offene Gesellschaft Kurpfalz URL 16:58 Raus auf die Straße USER


" Bewegung Halle"-Demo wächst , Demo am Montag schon mit 229 Teilnehmern , 29.11.2021 — Sonne lacht - Blende acht ! URL 2:01 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ unsere Kanäle und Gruppen USER USER USER ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ Bilder und Videos hochladen USER - USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


30.8 Zwönitz , 4 jährige Kinder wurden mit den Kindern festgehalten . Wir brauchen hier keine Parteien — MediaInformationCenter URL 28:33 Raus auf die Straßen USER


Bitte fleißig teilen und in den Status bei WhatsApp , Instagram , Facebook stellen oder direkt Freunde und Bekannte anschreiben . Lasst uns gemeinsam dafür sorgen , dass wir noch mehr werden als diesen Montag . # MV # Mo1312 # Neubrandenburg Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Just stay in Amsterdam lmfao . 🔗 UitAltijd ( USER Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Leipzig Nikolaikirche USER 29032021 - 05042021 - 12042021 - 19042021 - 26042021 Raus auf die Straße USER


Weitere Infos zu den Demos heute Annaberg-Buchholz URL Frankfurt ( Oder ) URL München URL Grimma URL Kempen URL Rostock URL Ulm URL Waiblingen URL USER - Bilder und Videos hochladen USER - Diskussion USER Fahren oder Mitfahren USER - Übernachten ? USER


Wer möchte darf daran teilnehmen 😉 👍 Es gehen die Verhandlungen im Mordfall Leonie weiter , gegen die Mutter . ! ! ! Schützt unsere Kinder ! ! ! 👍 💪 ❤ ️ # MV # Do0212 # Neubrandenburg Neue Fälle USER - Diskussion USER


Berlin 29.8.2021 , auch hier wieder ein riesiger Protestzug . Siehe wie viele wir wirklich sind ! — MediaInformationCenter URL 19:15 Raus auf die Straßen USER


Kapitol-Attacke : Gremium lädt Organisatoren von Trump-Kundgebung vor 👉 🏻 Neuer Beitrag Raus auf die Straßen USER 👉 Übersicht / Overview 👈


bundesweit USER Berlin URL URL Bremen URL Dresden ❌ URL Düsseldorf URL Hamburg URL Hannover URL Magdeburg URL Mainz ❌ URL Nürnberg URL Potsdam ❌ URL Sassnitz URL Schwerin URL URL Stuttgart ❌ URL URL Wiesbaden URL 15052021 Raus auf die Straße USER


Friseurin geht auf die Barrikaden . Ich bekomme keine Hilfe und brauche Essen . Verzweifelter Antuf beim Jobcenter und Entäuschung . USER


UK : Several hundred rally in Belfast against COVID passport - 04.12.2021 — demonstration_live URL 2:28 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Lichterlauf für Frieden Freiheit , Demokratie und Grundrechte . Mittwoch , 24.03.2021 18.30Uhr . 75031 Eppingen Versammlung / Aufzug ist angemeldet . USER 24032021 Raus auf die Straße USER


📆 Zusammenkunft für das Wohl unserer Kinder , der nächsten Generationen und ein Leben im Einklang mit der Erde und der Natur 👉 🏻 mehr Infos dazu # Termin # QuerDenken ! Bilder und Videos hochladen USER - Termine in Textform USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


Live aus dem Europäischen Parlament : Unterausschuss für Menschenrechte — Epoch Times Nachrichten URL 1:54:51 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Ihr Lieben , wie jeden Samstag , meditieren wir auch morgen , 14.8. , um 15.30 Uhr am Obstmarkt in der Fußgängerzone Kaufbeuren für Frieden , Freiheit , Wahrheit und Selbstbestimmung ! Wir freuen uns auf Euer Kommen ! ❤ ️ USER 14082021 Raus auf die Straße USER


Berlin- Köpi : Nach Angaben dieser über Lautsprecher zu hörenden Köpi-Bewohnerin , haben sich mehrere Menschen auf dem Wagenplatz auf Bäumen und hinter den Barrikaden so angekettet , dass eine Stürmung der Polizei ihr Leben gefährden würde . # b1510 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Chinapolitik : „ Wandel durch Annäherung “ ist gescheitert — Epoch Times Nachrichten URL 8:04 Raus auf die Straßen USER


Sozialverband : Obst und Gemüse werden für Arme zum Luxus — Epoch Times Nachrichten URL 3:08 Raus auf die Straßen USER


⚠ ️ WICHTIG FÜR ALLE DEMOKRATEN ⚠ ️ Anscheinend gehen die Demonstranten am Hauptbahnhof vorbei auf die Straße Alt-Moabit Richtung U-Bahnstation Turmstraße zu gehen!!️ # WirWerdenALLEdaSein # b2808 Raus auf die Straßen USER


🌅 ES WIRD HISTORISCH 🌅 🚀 BERLIN , 1. AUGUST 2021 🚀 ❤ ️ ✌ ️#WirwerdenALLEdasein ✌ ️ ❤ ️ Raus auf die Straße USER


Cloudcloud bekommt rechte — Weichreite TV URL 5:36 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Freitag , 30.04.2021 , 16:00 Demo vor Bahnhofspost Bamberg , Luitpoldstraße USER 30042021 Raus auf die Straße USER


Am 6. Dezember stehen wir zum 34. Mal auf dem Heumarkt in Köln und freuen uns über eure Unterstützung . USER 06122020 Bilder und Videos hochladen USER - Termine in Textform USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


Die Sensationelle und sehr emotionale Rede einer Ärztin in Dessau-Roßlau beim Familien-AUTOKORSO ❤ ️ ❤ ️ ❤ ️ Gänsehaut pur 🥰 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Flashmob vor dem Roten Rathaus in Berlin am 7. August 2021 — Querdenken 441 - Oldenburg URL 4:04 Raus auf die Straße USER


Weihnachtliches aus Gelsenkirchen . URL Wilhelm Schleweis Horster Str. 240 , 45897 Gelsenkirchen 0175 3773954 URL Raus auf die Straßen USER 👉 Übersicht / Overview 👈


17.12.2021 🛑 Livestream 🛑 2. Nauener Mahnwache am Rathausplatz Demo ab 19 Uhr — Berlin Online TV URL 1:53:03 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


🟢!!️LIVE AUS WIEN / / Wir stehen auf ! ! ! - Sonntag , 24.10.2021!!️ URL — — — — — — — — — — - 📰 Folge mir auf dem Kanal : URL 🗣 und rede mit : URL 💉 Solltest du dich für das Thema Nebenwirkung bei Corona-Impfungen interessieren : URL Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Indianerehrenwort : Azteken und Inkas schickten zu Epidemiezeiten ihre Häuptlinge zu den Göttern ... USER - Bilder und Videos hochladen - USER - Mitdenken USER Raus auf die Straße USER


Waiblingen Verkehrsstörungen in der Innenstadt , Verspätung und Ausfall von Buslinien , Verzögerung im Zugverkehr möglich Demoinfo URL 23112020 Bilder und Videos hochladen USER - Termine in Textform USER Fahren oder Mitfahren USER - Übernachten ? USER USER - USER - USER


Berlin vor dem Bundestag Mehr Details URL URL Karte URL Infektionsschutzgesetz URL USER 13042021 Raus auf die Straße USER


Poing Für die Demo heute 18h in Poing benötige ich unbedingt noch : 2 - 3 Ordner 18 - 19h 1 - 2 Helfer ab 17:30 Wer kann helfen ? ! ? Ist direkt an der S-Bahn , alle Materialien bringe ich mit ! USER USER USER - Bilder und Videos hochladen USER - Diskussion USER Fahren oder Mitfahren USER


Dissidenti in esilio , oppure si deve resistere in patria - Parole in libertà — Lafinanzasulweb URL 40:57 Raus auf die Straßen USER 👉 Übersicht / Overview 👈


Hamburg 18.09.2021 um 14 : 21 Uhr 6 Mannschaftstransporter mit Blaulicht von Osten kommend Richtung Stadtzentrum gesichtet Raus auf die Straßen USER


➡ ️ Protestmarsch am 20.03.2021 Liestal BL ⬅ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ ⬇ ️ 13.00 Uhr Besammlung Emma Herwegh-Platz 14.00 Uhr Abmarsch ca. 15.00 Uhr Kundgebung Schulanlage Frenken Bitte reist mit den öffentlichen Verkehrsmittel an ! Sie sind viele , WIR sind mehr ! Teilen Teilen Teilen Teilen Mehr URL USER 20032021 Raus auf die Straße USER


Am 18.07. findet die nächste Demo in Erbach ☮ 😉 Mit aufbauenden Reden und Musik und Tanz statt 🥳 📢 📢 Lebensfreude = Widerstand USER 18072021 Raus auf die Straße USER


via Schwindelambulanz Sinsheim / Dr. Bodo Schiffmann URL USER USER USER USER USER USER USER USER - Bilder und Videos hochladen USER - Diskussion USER Fahren oder Mitfahren USER

